### ISSUE TITLE
Remaining tmbench issues

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tools#105]
- [x] Add config option to change tx size
- [x] Make it more resilient to WSConn breaking
- [ ] Find source of WSConn breaking
- [ ] investigate how tmbench acts on clusters more
- [x] ensure that the way transactions are being sent at the provided rate is sensible
- [ ] ensure stats collection/computation is correct
- [ ] write tests for stats
- [ ] debug why a connection's tx send rate is significantly faster in the first block than in subsequent blocks

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1940
