### ISSUE TITLE
first test find out unmarshal data struct error

### ISSUE THREAD

**Issue by jianzi123** [tendermint/tools#107]
use tm-bench occur some error 

> [root@osd1 tm-bench]# tm-bench -test.v localhost:26657
> Status: Error unmarshalling rpc response result: invalid character -- Amino:JSON int/int64/uint/uint64 expects quoted values for javascript numeric support, got: 1044.
> 
then find in https://github.com/tendermint/go-amino/blob/master/json-decode.go#L118:14; but I can not fix it, thanks for any help.

**Comment by jianzi123** [comment]
@ValarDragon 

> [root@osd1 tm-bench]# tendermint version
> 0.21.0-46369a1a
>

**Comment by ValarDragon** [comment]
Oh woops. The current tm-bench is pointed at tendermints develop, whereas you are on master. Was using this for debugging earlier, hence pointing to develop, but it should remain pointed at tendermints master. (We're in the process of combining these repositories, so didn't realize it was going to be an issue -- my bad, sorry about that) I'll submit a PR to fix this. In the meantime, you can benchmark tendermint's develop if you want to (by making tendermint's develop branch), or just rebuild the version of tm-bench in the branch I'm about to create.

**Comment by jianzi123** [comment]
Thanks for your help, I woud change develop branch.
