### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by wojciechmalota** [tendermint/tools#112]
Hi,

I use the #111 version of monitor, together with tendermint ver. 0.22.0-rc2.
I have a cluster of 4 nodes, and the stats given by monitor look like:

```
2018-07-10 08:46:43.431720907 +0200 CEST m=+0.014158149 up 100.00%

Height: 0
Avg block time: 0.000 ms
Avg tx throughput: 0 per sec
Avg block latency: 1.739 ms
Active nodes: 4/4 (health: full) Validators: 0

NAME                    HEIGHT     BLOCK LATENCY     ONLINE     VALIDATOR
192.168.101.2:26657     0          0.512 ms          true       false
192.168.101.3:26657     0          0.561 ms          true       false
192.168.101.4:26657     0          0.531 ms          true       false
192.168.101.5:26657     0          0.595 ms          true       false
```
What I see is:
- Height is awlays 0
- Avg block timeis always 0
- Avg tx throughput is always 0
-  Validators is always 0
- VALIDATOR flag is always false

The cluster works fine so it's all about monitor itself.

**Comment by zramsay** [comment]
this repo is being deprecated (as of today), @wojciechmalota I've moved your issue to https://github.com/tendermint/tendermint/issues/1946
