### ISSUE TITLE
hub docker readme display last version as 0.9.0 instead of 0.10.0

### ISSUE THREAD

**Issue by antoineherzog** [tendermint/tools#35]
https://hub.docker.com/r/tendermint/tendermint/

**Comment by antoineherzog** [comment]
@adrianbrink here we go.

Also Ideally i think tendermint should not run with dummy by default. It is like you are running the ruby on rails standard docker with a sample app inside by default.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/560

**Comment by melekes** [comment]
thanks for reporting. fixed
