### ISSUE TITLE
Kubernetes script has maybe a small bug in the bash script

### ISSUE THREAD

**Issue by antoineherzog** [tendermint/tools#37]
As we got the error in our script, I fill this issue. I am not sure if this case is handle properly on the kubernetes however ..
In our case, It happenned sometimes that the nginx is working but the file is not copied yet so the script will failed.
Please find below a fix to the problem.
```
if curl -s "http://$v/pub_key.json" | grep "404 Not Found"
then
ERR=10
fi
  
  | while [ "$ERR" != 0 ]; do
  | sleep 5
  | curl -s "http://$v/pub_key.json" > /dev/null
  | ERR=$?
  |  
  | if curl -s "http://$v/pub_key.json" | grep "404 Not Found"
  | then
  | ERR=10
  | fi
  |  
  | done
```

**Comment by melekes** [comment]
@antoineherzog could you test https://github.com/tendermint/tools/pull/38 and see if it fixes the problem?

**Comment by antoineherzog** [comment]
@melekes sure, let me check

**Comment by antoineherzog** [comment]
@melekes i think we are good now!

**Comment by melekes** [comment]
Awesome! Thanks
