### ISSUE TITLE
[tm-monitor] Do we get our stats wrong?

### ISSUE THREAD

**Issue by melekes** [tendermint/tools#45]
Currently, we just listen for blocks (latencies,...) and provide a one-minute moving average.

0------
node:1 height:1 txs:200
node:2 height:1 txs:100
node:1 height:2 txs:100
1------
avg: 133

ethstats calculates avg by taking 64 nodes (ordered by height) and calculating the avg...
https://github.com/cubedro/eth-netstats/blob/5d3ed04c55314f05ce0f9b7fa3dfa8e4c7860720/lib/history.js#L539

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1939
