### ISSUE TITLE
[genesis] create initial implementation

### ISSUE THREAD

**Issue by melekes** [tendermint/tools#48]
We need a tool, which will help us form `genesis.json` file. The simplest implementation would be a web server, which has 2 routes:

```
POST /validator?pubkey=...&push_genesis_file_to=http://{IP}:46657/api/...
GET /genesis.json
```

A validator can be added to `genesis.json` by sending a POST request to `/validator`. Note, the web server should only allow changing `genesis.json` until `--min-wait` or `--min-vals` reached.

When `min-wait` time is passed or `min-vals` number is reached, this tool should create a file (plus backup on disk) and push it to all registered validators (**we will need an endpoint in Tendermint for that**). Alternatively, a node or validator can request current `genesis.json` by sending a GET request to `/genesis.json` (note it should respond with 404 while it forms a genesis file).

Another genesis parts like `app_options` can be provided with the template (`-template` flag which is `./genesis.json.tmpl` by default) during start.

UPD 1. remove min-wait/min-vals. all validators should check in before start
UPD 2. validators should ping this tool for genesis.json (so no push)
UPD 3. add support for multiple chains
UPD 4. use etcd as an underlying storage?

**Comment by melekes** [comment]
I am not a fan of pushing the resulting file back to validators because we'll have to store them somewhere, which in turn makes it security issue (attacker can fetch all validator IPs). But maybe this is OK for private clouds.

**Comment by melekes** [comment]
Later we will probably need to make this tool fault-tolerant. @ebuchman proposed something like etcd/consul or "ideally tendemint plus merkleeyes". Not really sure we need these though. What I would suggest is to add a few slaves and a sync backup. The reasoning is that we need consensus only while forming a genesis file (but again, maybe we don't need this stage to be fault-tolerant cause it is very short - like 10 min). Later on, when we just serving the resulting genesis file, any slave can do that even if the master is down.

**Comment by ebuchman** [comment]
I don't think we should push it out to validators. Nodes should ping the genesis endpoint until it returns successfully. 

Also, do we even want `min-time` ? What's the use case for having less than the min number of validators? 

>  Not really sure we need these though.

I'm thinking more along the lines of highly-available fault tolerant service that tracks many chains and serves as the endpoint for starting new ones. So it can track ips of validators as well and continue to host the genesis so that new nodes can sync up. Not a priority for now though

**Comment by melekes** [comment]
kkkkkkk
