### ISSUE TITLE
hi,all, I encountered the following problems when i run "make  create",why? How can we solve this problem?

### ISSUE THREAD

**Issue by hsin11** [tendermint/tools#50]
root@sin:~#git clone https://github.com/tendermint/tools.git && cd tools/mintnet-kubernetes/examples/basecoin 
root@sin:~/tools/mintnet-kubernetes/examples/basecoin# make create
==> Creating deployment
/usr/local/bin/kubectl: 1: /usr/local/bin/kubectl: Syntax error: redirection unexpected
Makefile:2: recipe for target 'create' failed
make: *** [create] Error 2

**Comment by melekes** [comment]
What Kubernetes version?

**Comment by zramsay** [comment]
@hsin11 please see [this documentation](http://tendermint.readthedocs.io/projects/tools/en/develop/deploy-testnets.html) for setting up testnets and deployments. Let us know if it still doesn't work.
