### ISSUE TITLE
tm-bench build error

### ISSUE THREAD

**Issue by vinodenginelab** [tendermint/tools#53]
Facing below error during build of tm-bench:

# github.com/tendermint/tools/tm-monitor/eventmeter
../tm-monitor/eventmeter/eventmeter.go:131: em.wsc.Conn undefined (type *rpcclient.WSClient has no field or method Conn, but does have rpcclient.conn)
../tm-monitor/eventmeter/eventmeter.go:179: not enough arguments in call to em.wsc.Subscribe
../tm-monitor/eventmeter/eventmeter.go:197: not enough arguments in call to em.wsc.Unsubscribe
../tm-monitor/eventmeter/eventmeter.go:239: not enough arguments in call to em.wsc.Subscribe
../tm-monitor/eventmeter/eventmeter.go:299: em.wsc.Conn undefined (type *rpcclient.WSClient has no field or method Conn, but does have rpcclient.conn)

**Comment by melekes** [comment]
This will most likely be resolved by #44

**Comment by melekes** [comment]
@vinodenginelab could you please try again with the new code (don't forget to `git pull`). If the error persists, try glide (`make get_vendor_deps`).
