### ISSUE TITLE
tm-bench not working properly

### ISSUE THREAD

**Issue by rahulltkr** [tendermint/tools#54]
I am using [tm-bench](https://hub.docker.com/r/tendermint/bench/) command available in docker container. Copied binary file from container to host machine. tm-bench command not accepting tcp://  as prefix. Without adding prefix it showing warning to added prefix. 

Error: 
dial tcp: address tcp:%2F%2F127.0.0.1:46657: too many colons in address

Also tm-bench is running without any transactions 

https://www.screencast.com/t/tExmvf4D

tendermint version: 0.11.0-'7682ad9

**Comment by melekes** [comment]
What application are you running? Could you please try running TM with debug log level (`--log_level="*:debug"`)?

**Comment by rahulltkr** [comment]
tendermint is running with dummy application as below. I have also used abci app dummy application.

tendermint node --proxy_app=dummy

```
Running 5s test @ 127.0.0.1:46657
WARN[10-06|04:28:56] WARNING (go-rpc): Please use fully formed listening addresses, including the tcp:// or unix:// prefix module=rpcclient
WARN[10-06|04:28:56] WARNING (go-rpc): Please use fully formed listening addresses, including the tcp:// or unix:// prefix module=rpcclient
INFO[10-06|04:28:56] Starting WSClient                        module=rpcclient impl="127.0.0.1:46657, /websocket"
Stats             Avg        Stdev      Max
Block latency     0.17ms     0.01ms     0ms
Blocks/sec        0.000      0.000      0
Txs/sec           0          0          0
```
I found one error in tendermint logs when tm-bench finished as below.. 

E[10-06|04:29:01.471] Failed to read request                       module=rpc-server protocol=websocket remote=127.0.0.1:58580 err="websocket: close 1006 (abnormal closure): unexpected EOF"

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tools/commit/989ff83c4c1894a03b7d2ac4a2a19fa7a7c4c37b

**Comment by melekes** [comment]
@rahulltkr could you please try tm-bench `v0.2.0` and let me know the results

**Comment by rahulltkr** [comment]
Hi @melekes , Latest version from docker hub is working now... Thanks a lot
