### ISSUE TITLE
tm-bench command with different transactions and transaction sizes

### ISSUE THREAD

**Issue by Ajita24** [tendermint/tools#66]
Hello
I am trying to run tm-bench command with varying number of transactions on different transaction sizes(made code changes for this and build successfully) in the following manner on validator nodes:

`tm-bench_500 -T 600 -v -r 600 -c 1 54.67.122.49:46657;tm-bench_1000 -T 300 -v -r 200 -c 1 54.67.122.49:46657;tm-bench_10000 -T 300 -v -r 150 -c 1 54.67.122.49:46657;tm-bench_15000 -T 300 -v -r 50 -c 1 54.67.122.49:46657 `

The results obtained are:

2-01|09:00:04.758] sent 600 transactions                       
Stats             Avg         Stdev      Max
Block latency     74.67ms     3.11ms     74ms
Blocks/sec        0.007       0.081      1
Txs/sec           5           74         1409

I[12-01|09:05:05.454] sent 200 transactions                      
Stats             Avg         Stdev      Max
Block latency     75.53ms     4.71ms     85ms
Blocks/sec        0.003       0.058      1
Txs/sec           33          577        10000

I[12-01|09:10:06.213] sent 150 transactions                       
Stats             Avg         Stdev      Max
Block latency     74.56ms     4.39ms     74ms
Blocks/sec        0.000       0.000      0
Txs/sec           0           0          0

I[12-01|09:15:06.910] sent 50 transactions                         
Stats             Avg         Stdev      Max
Block latency     74.53ms     4.39ms     74ms
Blocks/sec        0.000       0.000      0
Txs/sec           0           0          0

why does it show 0 txs/sec when 150 transactions are sent of 10000bytes and same for 50 transactions.

```

Getting errors :
I[12-01|11:21:46.578] sent 50 transactions  addr=54.67.12 2.49:46657 took=21.555616ms
E[12-01|11:21:46.624] failed to read response module=rpcclient node=54.67.122.49:46657 err="websocket: close 1006 (abnormal closure): unexpected EOF"
I[12-01|11:21:46.624] reconnecting  module=rpcclient node=54.67.122.49:46657 attempt=1
I[12-01|11:21:46.649] status node=54.67.122.49:46657 down=(MISSING)
I[12-01|11:21:47.579] sent 50 transactions addr=54.67.122.49:46657 took=21.604571ms

```

**Comment by melekes** [comment]
Thanks for reporting this. I will take a look when I have time. Been busy lately

**Comment by melekes** [comment]
Refs #45

**Comment by melekes** [comment]
Could you please provide tendermint log?

Also, this may be related to https://github.com/tendermint/tools/issues/62

**Comment by melekes** [comment]
I reimplemented tm-bench in #62. Please try the new version and let us know if that does not work for you.
