### ISSUE TITLE
Code changes not reflecting in tm-bench

### ISSUE THREAD

**Issue by Ajita24** [tendermint/tools#67]
Hello

I want to make some code changes in tm-bench code but even the simplest changes and then running command "make build", the changes are not reflecting. In order to check I added a simple code to print some text (screenshot- https://www.screencast.com/t/nQSxlj20Iy ) but still statistics heading shows no changes(screenshot - https://www.screencast.com/t/I60nDhZCfzK0).

Am I doing something wrong or missing something? Please guide. How can I make code changes in tm-bench code and make it work.

Thanks

**Comment by zramsay** [comment]
Hi @Ajita24, try this:
```
make get_vendor_deps
make build
./tm-bench 
```
should work; I just tried it on latest master. Note that `make build` will output the binary in the repo's root, whereas `make install` will make the binary globally accessible. The former requires the `./` prior to the command whereas the latter doesn't and can be run from anywhere. So if `tm-bench` is installed globally then you run `make build`, make sure to use `./tm-bench` after applying your changes. Hope this helps!

**Comment by melekes** [comment]
Yeah, you're probably running old binary. See the comment above.

**Comment by Ajita24** [comment]
@Thanks!! the comment solved the issue.
