### ISSUE TITLE
Error starting mintnet-kubernetes basecoin example: status - ImagePullBackOff

### ISSUE THREAD

**Issue by SurabhiBorgikar** [tendermint/tools#72]
Error while starting mintnet-kubernetes basecoin example. The pod status is: ImagePullBackOff. The tendermint/basecoin image is not available in the docker repository. 

Created a basecoin image using the steps specified here:
http://tendermint.readthedocs.io/projects/tools/en/develop/tools/docker.html

In pod tm-0, pub-key container logs are:- 

`+ mkdir -p /usr/share/nginx`
`+ cp /tendermint/pub_key.json /usr/share/nginx/pub_key.json`
`+ cp /app/pub_key.json /usr/share/nginx/app_pub_key.json`
`cp: cannot stat '/app/pub_key.json': No such file or directory`

Is there a specific version of basecoin to used for this setup?

Thanks!

**Comment by melekes** [comment]
basecoin is deprecated. see https://github.com/cosmos/cosmos-sdk

TODO:
- [ ] remove basecoin example
- [ ] check k8s still works
- [ ] update k8s examples to use newer TM

**Comment by melekes** [comment]
@SurabhiBorgikar is this something you wanna help us out?

**Comment by SurabhiBorgikar** [comment]
@melekes sure I'd be glad to help. Will start with what's included in the todo.

**Comment by melekes** [comment]
@SurabhiBorgikar did you have a chance to work on this?

**Comment by zramsay** [comment]
@SurabhiBorgikar these files have been updated and moved to the tendermint repo: try running these commands: https://github.com/tendermint/tendermint/blob/5727916c5b31748714dc6a23742ee44a40e85a75/Makefile#L193-L201

or see the example (starting from a fresh DO Ubuntu instance here: https://github.com/tendermint/tendermint/blob/develop/networks/remote/integration.sh

**Comment by zramsay** [comment]
edit: we're keeping mintnet-kubernetes around FTTB

**Comment by zramsay** [comment]
move issue to https://github.com/tendermint/tendermint/issues/1941
