### ISSUE TITLE
mintet-kubernetes basecoin setup issue

### ISSUE THREAD

**Issue by aastein** [tendermint/tools#73]
Following the MacOS guide here <a href="https://github.com/tendermint/tools/blob/master/mintnet-kubernetes/README.rst">tendermint/tools/mintnet-kubernetes/README.rst</a>

This part gives an error:
```sh
$ make create
Error from server (NotFound): the server could not find the requested resource
```

**Comment by melekes** [comment]
basecoin is deprecated. kubernetes scripts might need to be updated. wanna help out?

**Comment by melekes** [comment]
see https://github.com/tendermint/tools/issues/72#issuecomment-355886874
